packaging_format = 2

id = "teddit"
name = "Teddit"
description.en = "Open source alternative Reddit front-end"
description.fr = "Front-end libre alternatif à Reddit"

version = "0.4.0~ynh5"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://teddit.net/"
demo = "https://teddit.net/"
code = "https://codeberg.org/teddit/teddit"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Teddit will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Teddit sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://codeberg.org/teddit/teddit/archive/4536a7f4608f0f17bbee4188f9875fad8bfa954f.tar.gz"
        sha256 = "e2806688d171c6ec5e0e63d0e3ae3ac4c35e125a4d750c7f74187407d7565c0e"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "ffmpeg"
